apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sample-app
      service: producer
  template:
    metadata:
      labels:
        app: sample-app
        service: producer
    spec:
      containers:
        - name: producer
          image: fagot013/cc-auth-producer:1.0